AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An AWS Serverless Application that uses the ASP.NET Core framework running in
  Amazon Lambda.

Globals:
  Api:
    Cors: 
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"

Parameters:
  AspNetCoreEnv:
    Type: String
    Default: Development
  UserpoolArn:
    Type: String
    Default: arn:aws:cognito-idp:ap-southeast-2:869393488965:userpool/ap-southeast-2_AqzplwcCO

Resources:

  CarbudsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: CognitoUserPool
        Authorizers:
          CognitoUserPool:
            UserPoolArn: !Ref UserpoolArn
        AddDefaultAuthorizerToCorsPreflight: false

  AspNetCoreApi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: CPT331.Carbuds.Api::CPT331.Carbuds.Api.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: ''
      MemorySize: 1024
      Timeout: 30
      Role: null
      Policies:
        - AWSLambda_FullAccess
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonCognitoPowerUser
        - Statement:
          - Sid: SSMParametersPolicy
            Effect: Allow
            Action:
            - ssm:GetParameter
            - ssm:GetParameters
            - ssm:GetParametersByPath
            Resource: '*'
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: !Ref AspNetCoreEnv
      Events:

        #------------- Auth -------------
        AuthLogin:
          Type: Api
          Properties:
            Path: '/api/auth/login'
            Method: Post
            RestApiId: !Ref "CarbudsApi" 
            Auth:
              Authorizer: 'NONE'

        #------------- Bookings -------------
        Bookings:
          Type: Api
          Properties:
            Path: '/api/booking/{all+}'
            Method: ANY
            RestApiId: !Ref "CarbudsApi" 

        #------------- Cars -------------
        Cars:
          Type: Api
          Properties:
            Path: '/api/cars/{all+}'
            Method: ANY
            RestApiId: !Ref "CarbudsApi" 

        #------------- Parking Location -------------
        ParkingLocationAddUpdateParkingLocation:
          Type: Api
          Properties:
            Path: '/api/parkingLocation/{all+}'
            Method: ANY
            RestApiId: !Ref "CarbudsApi" 

        #------------- User -------------
        UserSignup:
          Type: Api
          Properties:
            Path: '/api/user/usersignup'
            Method: Post
            RestApiId: !Ref "CarbudsApi" 
            Auth:
              Authorizer: 'NONE'

        UserVerify:
          Type: Api
          Properties:
            Path: '/api/user/verify'
            Method: Post
            RestApiId: !Ref "CarbudsApi" 
            Auth:
              Authorizer: 'NONE'

  # ---------------- DYNAMO TABLE DEFINITIONS ----------------
  
  CarsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: Uuid
          AttributeType: S
      KeySchema:
        - AttributeName: Uuid
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: carbuds-cars

  UserProfilesTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: Email
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: carbuds-userProfiles

  ParkingLocationsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: Uuid
          AttributeType: S
        - AttributeName: Longitude
          AttributeType: N
        - AttributeName: Latitude
          AttributeType: N
      KeySchema:
        - AttributeName: Uuid
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: LongitudeIndex
          KeySchema:
          - AttributeName: Longitude
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - domain
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: LatitudeIndex
          KeySchema:
          - AttributeName: Latitude
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - domain
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: carbuds-parkingLocations

  BookingsTableV2:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: Uuid
          AttributeType: S
        - AttributeName: UserEmail
          AttributeType: S
        - AttributeName: CarUuid
          AttributeType: S
      KeySchema:
        - AttributeName: Uuid
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserEmailIndexV2
          KeySchema:
          - AttributeName: UserEmail
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: CarUuidIndexV2
          KeySchema:
          - AttributeName: CarUuid
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: carbuds-bookings-v2

  CarParkingAllocationsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: CarUuid
          AttributeType: S
        - AttributeName: LocationUuid
          AttributeType: S
      KeySchema:
        - AttributeName: CarUuid
          KeyType: HASH
        - AttributeName: LocationUuid
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: LocationIndex
          KeySchema:
          - AttributeName: LocationUuid
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - domain
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: carbuds-carParkingAllocations

Outputs:
  ApiURL:
    Description: raw API endpoint URL for this environment
    Value: !Sub 'https://${CarbudsApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/'