AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An AWS Serverless Application that uses the ASP.NET Core framework running in
  Amazon Lambda.

Globals:
  Api:
    Cors: 
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"

Parameters:
  AspNetCoreEnv:
    Type: String
    Default: Development
  UserpoolArn:
    Type: String
    Default: arn:aws:cognito-idp:ap-southeast-2:869393488965:userpool/ap-southeast-2_AqzplwcCO

Resources:

  CarbudsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: CognitoUserPool
        Authorizers:
          CognitoUserPool:
            UserPoolArn: !Ref UserpoolArn
        AddDefaultAuthorizerToCorsPreflight: false

  AspNetCoreApi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: CPT331.Carbuds.Api::CPT331.Carbuds.Api.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: ''
      MemorySize: 1024
      Timeout: 30
      Role: null
      Policies:
        - AWSLambda_FullAccess
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
        - Statement:
          - Sid: SSMParametersPolicy
            Effect: Allow
            Action:
            - ssm:GetParameter
            - ssm:GetParameters
            - ssm:GetParametersByPath
            Resource: '*'
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: !Ref AspNetCoreEnv
      Events:

        #------------- Auth -------------
        AuthLogin:
          Type: Api
          Properties:
            Path: '/api/auth/login'
            Method: Post
            RestApiId: !Ref "CarbudsApi" 

        #------------- Cars -------------
        CarsAddUpdateCar:
          Type: Api
          Properties:
            Path: '/api/cars'
            Method: Post
            RestApiId: !Ref "CarbudsApi" 

        CarsListAllCars:
          Type: Api
          Properties:
            Path: '/api/cars/list'
            Method: Get
            RestApiId: !Ref "CarbudsApi" 

  # ---------------- DYNAMO TABLE DEFINITIONS ----------------
  
  CarsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: Uuid
          AttributeType: S
      KeySchema:
        - AttributeName: Uuid
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: carbuds-cars

  UserProfilesTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: Email
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: carbuds-userProfiles

  ParkingLocationsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: Uuid
          AttributeType: S
        - AttributeName: Longitude
          AttributeType: N
        - AttributeName: Latitude
          AttributeType: N
      KeySchema:
        - AttributeName: Uuid
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: LongitudeIndex
          KeySchema:
          - AttributeName: Longitude
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - domain
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: LatitudeIndex
          KeySchema:
          - AttributeName: Latitude
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - domain
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: carbuds-parkingLocations

  CarParkingAllocationsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: CarUuid
          AttributeType: S
        - AttributeName: LocationUuid
          AttributeType: S
      KeySchema:
        - AttributeName: CarUuid
          KeyType: HASH
        - AttributeName: LocationUuid
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: carbuds-carParkingAllocations

Outputs:
  ApiURL:
    Description: raw API endpoint URL for this environment
    Value: !Sub 'https://${CarbudsApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/'